name: Bigquery dedicated env

on:
  pull_request:
    types: [closed, unlabeled, labeled, synchronize]

jobs:
  dedicated:
    if:  |
      github.event.label.name == 'dedicated_bigquery' ||
      (github.event.action == 'closed' && contains(github.event.pull_request.labels.*.name, 'dedicated_bigquery')) ||
      (github.event.action == 'synchronize' && contains(github.event.pull_request.labels.*.name, 'dedicated_bigquery'))
    runs-on: ubuntu-20.04     
    steps:
      - uses: actions/checkout@v3
      - name: declare variables
        run: |
          if [[ ${{ github.event_name }} = "workflow_dispatch" ]]; then
            echo "BQ_PREFIX=dedicated_release_${{ github.event.inputs.version }}_" >> $GITHUB_ENV
          else
            echo "BQ_PREFIX=dedicated_${{ github.event.pull_request.number }}_" >> $GITHUB_ENV
          fi
      - name: deploy-bq
        run: |
          echo ${{ github.event }}
          echo ${{ github.event.action }}
          echo ${{ github.event_name }}
          echo "deploy bigquery prefix ${BQ_PREFIX}"
