name: Bigquery dedicated env

on:
  pull_request:
    types: [closed, unlabeled, labeled, synchronize]
  workflow_call:
    inputs:
      bq-version:
        type: string
        required: true

jobs:
  dedicated:
    if: |
      github.event_name == 'workflow_dispatch' && github.event.inputs.version != ''
    runs-on: ubuntu-20.04     
    steps:
      - uses: actions/checkout@v3
      - name: declare variables
        run: |
          if [[ ${{ github.event_name }} = "workflow_dispatch" ]]; then
            echo "BQ_PREFIX=dedicated_release_${{ github.event.inputs.version }}_" >> $GITHUB_ENV
          else
            echo "BQ_PREFIX=dedicated_${{ github.event.pull_request.number }}_" >> $GITHUB_ENV
          fi
      - name: deploy-bq
        run: |
          echo "deploy bigquery tag ${{ github.event.inputs.bq-version }}"
          echo ${{ github.event }}
          echo ${{ github.event.action }}
          echo ${{ github.event_name }}
          echo "deploy bigquery prefix ${BQ_PREFIX}"
