name: "Draft new release"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version you want to release in format yyyyy-MM, for example 2022-10'
        required: true

jobs:
  draft-new-release:
    name: "Draft a new release"
    runs-on: ubuntu-latest
    outputs:
      change_bq: ${{ steps.changes.outputs.bigquery }}
      change_db: ${{ steps.changes.outputs.databricks }}
      change_pg: ${{ steps.changes.outputs.postgres }}
      change_rs: ${{ steps.changes.outputs.redshift }}
      change_sf: ${{ steps.changes.outputs.snowflake }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            bigquery:
              - 'clouds/bigquery/version'
            databricks:
              - 'clouds/databricks/version'
            postgres:
              - 'clouds/postgres/version'
            redshift:
              - 'clouds/redshift/version'
            snowflake:
              - 'clouds/snowflake/version'
          base: stable
      - name: Update bq changelog
        if: steps.changes.outputs.bigquery == 'true'
        run: |
          VERSION=$(cat clouds/bigquery/version)
          echo "BQ_VERSION=$VERSION" >> $GITHUB_OUTPUT         
          sed -i "s/\[Unreleased\]/\[${VERSION}\] - ${{ github.event.inputs.version }}/g" clouds/bigquery/CHANGELOG.md
      - name: Update databricks changelog
        if: steps.changes.outputs.databricks == 'true'
        run: |
          VERSION=$(cat clouds/snowflake/version)
          echo "DB_VERSION=$VERSION" >> $GITHUB_OUTPUT         
          sed -i "s/\[Unreleased\]/\[${VERSION}\] - ${{ github.event.inputs.version }}/g" clouds/databricks/CHANGELOG.md
      - name: Update postgres changelog
        if: steps.changes.outputs.postgres == 'true'
        run: |
          VERSION=$(cat clouds/snowflake/version)
          echo "PG_VERSION=$VERSION" >> $GITHUB_OUTPUT         
          sed -i "s/\[Unreleased\]/\[${VERSION}\] - ${{ github.event.inputs.version }}/g" clouds/postgres/CHANGELOG.md
      - name: Update redshift changelog
        if: steps.changes.outputs.redshift == 'true'
        run: |
          VERSION=$(cat clouds/snowflake/version)
          echo "RS_VERSION=$VERSION" >> $GITHUB_OUTPUT         
          sed -i "s/\[Unreleased\]/\[${VERSION}\] - ${{ github.event.inputs.version }}/g" clouds/redshift/CHANGELOG.md
      - name: Update snowflake changelog
        if: steps.changes.outputs.snowflake == 'true'
        run: |
          VERSION=$(cat clouds/snowflake/version)
          echo "SF_VERSION=$VERSION" >> $GITHUB_OUTPUT         
          sed -i "s/\[Unreleased\]/\[${VERSION}\] - ${{ github.event.inputs.version }}/g" clouds/snowflake/CHANGELOG.md
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: edit changelog versions
          branch: release/${{ github.event.inputs.version }}
          create_branch: true
      - name: Create pull request
        uses: thomaseizinger/create-pull-request@1.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          head: release/${{ github.event.inputs.version }}
          base: stable
          title: Release version ${{ github.event.inputs.version }}
          reviewers: ${{ github.actor }} 
          body: |
            Hi @${{ github.actor }}!
            This PR was created in response to a manual trigger of the release workflow here: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}.
            Please, check that the version files and changelogs are correct.
            Merging this PR will create a GitHub release and publish the AT libraries for the DW whose versions have been updated

      - name: Trigger update doc job
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        run: gh workflow run -R https://github.com/CartoDB/documentation.git update-doc.yml -f version=new-${{ github.event.inputs.version }}

  deploy-bq:
    uses: aarroyosal/AT-poc/.github/workflows/bigquery-ded.yml@main
    needs: draft-new-release
    if: needs.draft-new-release.outputs.change_bq == 'true'
    name: "Deploy AT for BigQuery"
    with:
      bq_version: 1.5.5
  deploy-db:
    needs: draft-new-release
    if: needs.draft-new-release.outputs.change_db == 'true'
    name: "Deploy AT for Databricks"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: deploy-db
        run: |
          DB_VERSION=$(cat clouds/databricks/version)
          echo "deploy databricks tag ${DB_VERSION}"

  deploy-pg:
    needs: draft-new-release
    if: needs.draft-new-release.outputs.change_pg == 'true'
    name: "Deploy AT for Postgres"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: deploy-pg
        run: |
          PG_VERSION=$(cat clouds/postgres/version)
          echo "deploy postgres tag ${PG_VERSION}"

  deploy-rs:
    needs: draft-new-release
    if: needs.draft-new-release.outputs.change_rs == 'true'
    name: "Deploy AT for Redshift"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: deploy-rs
        run: |
          RS_VERSION=$(cat clouds/redshift/version)
          echo "deploy redshift tag ${RS_VERSION}"

  deploy-sf:
    needs: draft-new-release
    if: needs.draft-new-release.outputs.change_sf == 'true'
    name: "Deploy AT for Snowflake"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: deploy-sf
        run: |
          SF_VERSION=$(cat clouds/snowflake/version)
          echo "deploy snowflake tag ${SF_VERSION}}"



