on: workflow_dispatch
name: pre-release
jobs:
  pre-release:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          monorepo-tags: true
          command: manifest-pr
