on: workflow_dispatch
name: release
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: tag-release
        with:
          command: manifest
          monorepo-tags: true
      - run: echo "${{ steps.tag-release.outputs }}"
      - name: publish-bq
        if: ${{ steps.release.outputs['clouds/bigquery--bq'] }}
        run: echo "publish bigquery"
      - name: publish-db
        if: ${{ steps.release.outputs['clouds/databricks--db'] }}
        run: echo "publish databricks"
      - name: publish-pg
        if: ${{ steps.release.outputs['clouds/postgres--pg'] }}
        run: echo "publish postgres"
      - name: publish-rs
        if: ${{ steps.release.outputs['clouds/redshift--rs'] }}
        run: echo "publish redshift"
      - name: publish-sf
        if: ${{ steps.release.outputs['clouds/snowflake--sf'] }}
        run: echo "publish snowflake"