on: workflow_dispatch
name: release
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: tag-release
        with:
          command: manifest
          monorepo-tags: true
      - run: echo "releases created: ${{ steps.tag-release.releases_created }}"
        if: ${{ steps.tag-release.releases_created }}
      - name: publish-bq
        if: ${{ steps.release.outputs['clouds/bigquery--release_created'] }}
        run: echo "publish bigquery tag ${{ steps.release.outputs['clouds/bigquery--tag_name'] }}"
      - name: publish-db
        if: ${{ steps.release.outputs['clouds/databricks--release_created'] }}
        run: echo "publish databricks tag ${{ steps.release.outputs['clouds/databricks--tag_name'] }}"
      - name: publish-pg
        if: ${{ steps.release.outputs['clouds/postgres--release_created'] }}
        run: echo "publish postgres tag ${{ steps.release.outputs['clouds/postgres--tag_name'] }}"
      - name: publish-rs
        if: ${{ steps.release.outputs['clouds/redshift--release_created'] }}
        run: echo "publish redshift tag ${{ steps.release.outputs['clouds/redshift--tag_name'] }}"
      - name: publish-sf
        if: ${{ steps.release.outputs['clouds/snowflake--release_created'] }}
        run: echo "publish snowflake tag ${{ steps.release.outputs['clouds/snowflake--tag_name'] }}"